<?php
$products = [
    [
        'id' => 1,
        'name' => "Brownie Tradicional",
        'price' => 8.90,
        'image' => "img/products/product-1.png",
        'description' => "Nosso clássico brownie feito com chocolate belga. Textura macia, sabor intenso e irresistível.",
        'is_bestseller' => false,
        'is_featured' => false,
        'is_new' => false,
        'rating' => 4.8,
        'reviews_count' => 89
    ],
    [
        'id' => 2,
        'name' => "Brownie com Recheio Branco",
        'price' => 15.90,
        'image' => "img/products/product-2.png",
        'description' => "Brownie no pote com recheio branco cremoso. Textura úmida e camadas que derretem na boca.",
        'is_bestseller' => false,
        'is_featured' => false,
        'is_new' => false,
        'rating' => 4.9,
    ],
    [
        'id' => 3,
        'name' => "Brownie com Recheio Preto",
        'price' => 12.50,
        'image' => "img/products/product-3.png",
        'description' => "Brownie com recheio de brigadeiro gourmet cremoso. Para os amantes de chocolate intenso!",
        'is_bestseller' => false,
        'is_featured' => false,
        'is_new' => false,
        'rating' => 4.7,
        'reviews_count' => 67
    ],
    [
        'id' => 4,
        'name' => "Brownie com Recheio de Maracujá",
        'price' => 20.90,
        'image' => "img/products/product-4.png",
        'description' => "A perfeita união entre o doce do brownie e o azedinho do maracujá. Uma experiência tropical e envolvente.",
        'is_bestseller' => false,
        'is_featured' => false,
        'is_new' => false,
        'rating' => 4.8,
        'reviews_count' => 92,
    ],
    [
        'id' => 5,
        'name' => "Brownie com Recheio de Oreo",
        'price' => 13.90,
        'image' => "img/products/product-5.png",
        'description' => "Brownie recheado com creme de avelã e pedaços crocantes de Oreo. Uma explosão de sabor!",
        'is_bestseller' => false,
        'is_featured' => true,
        'is_new' => false,
        'rating' => 4.7,
        'reviews_count' => 78,
        'badge' => 'MAIS VENDIDO',
    ],
    [
        'id' => 6,
        'name' => "Brownie com Recheio de Creme",
        'price' => 45.90,
        'image' => "img/products/product-6.png",
        'description' => "Kit com 6 brownies recheados com creme branco e ao leite. Ideal para presentear e saborear diversos sabores.",
        'is_bestseller' => false,
        'is_featured' => false,
        'is_new' => false,
        'rating' => 4.9,
        'reviews_count' => 34,
    ],
    [
        'id' => 7,
        'name' => "Brownie com Recheio de Bolo",
        'price' => 16.90,
        'image' => "img/products/product-7.png",
        'description' => "Brownie recheado com massa de bolo macia e saborosa. Um contraste de texturas que surpreende!",
        'is_bestseller' => false,
        'is_featured' => false,
        'is_new' => false,
        'rating' => 4.8,
        'reviews_count' => 23,
        'badge' => 'NOVIDADE'
    ],
    [
        'id' => 8,
        'name' => "Brownie de Ferrero Rocher",
        'price' => 14.90,
        'image' => "img/products/product-8.png",
        'description' => "Brownie com pedaços de Ferrero Rocher e creme de avelã. Sabor sofisticado para paladares exigentes.",
        'is_bestseller' => false,
        'is_featured' => true,
        'is_new' => false,
        'rating' => 4.8,
        'reviews_count' => 65
    ],
    [
        'id' => 9,
        'name' => "Brownie de Nutella com Ferrero Rocher",
        'price' => 15.50,
        'image' => "img/products/product-9.png",
        'description' => "A combinação perfeita: Nutella cremosa com pedaços de Ferrero Rocher no brownie. Um verdadeiro luxo!",
        'is_bestseller' => true,
        'is_featured' => false,
        'is_new' => false,
        'rating' => 4.7,
        'reviews_count' => 156,
        'stock_warning' => 'Não perca essa oportunidade!',
        'spotlight_category' => 'Edição Especial',
        'spotlight_badge' => 'NOSSO BEST-SELLER',
        'old_price' => 18.90,
        'discount' => 15,
         'features' => [
            'Ingredientes premium',
            'Sem conservantes', 
            'Validade: 7 dias refrigerado'
        ],
    ],
    [
        'id' => 10,
        'name' => "Brownie de Nutella com Bombom",
        'price' => 17.90,
        'image' => "img/products/product-10.png",
        'description' => "Brownie gourmet recheado com Nutella e bombom crocante. Um sabor marcante e envolvente.",
        'is_bestseller' => false,
        'is_featured' => true,
        'is_new' => false,
        'rating' => 4.7,
        'reviews_count' => 38
    ],
    [
        'id' => 11,
        'name' => "Brownie com Coco Queimado",
        'price' => 13.50,
        'image' => "img/products/product-11.png",
        'description' => "Brownie com cobertura de coco queimado crocante. Um toque tropical com sabor inconfundível.",
        'is_bestseller' => false,
        'is_featured' => false,
        'is_new' => false,
        'rating' => 4.6,
        'reviews_count' => 42
    ],
    [
        'id' => 12,
        'name' => "Brownie com Recheio de Red Velvet",
        'price' => 13.50,
        'image' => "img/products/product-12.png",
        'description' => "Brownie recheado com massa red velvet e cobertura de cream cheese. Delicado, vibrante e irresistível.",
        'is_bestseller' => false,
        'is_featured' => false,
        'is_new' => false,
        'rating' => 4.7,
        'reviews_count' => 51
    ],
    [
        'id' => 13,
        'name' => "Combo Degustação de 6 Mini Brownies",
        'price' => 14.90,
        'image' => "img/products/product-13.png",
        'description' => "Uma seleção de nossos melhores brownies em um só combo. Ideal para quem quer experimentar todos os sabores!",
        'is_bestseller' => false,
        'is_featured' => false,
        'is_new' => false,
        'rating' => 4.8,
        'reviews_count' => 29
    ],

    [
        'id' => 14,
        'name' => "Caixa Clássica (6 Brownies)",
        'price' => 49.90,
        'image' => "img/products/product-6.png",
        'description' => "Seis brownies sortidos em embalagem especial para presentear.",
        'is_bestseller' => false,
        'is_featured' => false,
        'is_new' => false,
        'rating' => 4.9,
        'reviews_count' => 15,
        'is_box' => true
    ],
    [
        'id' => 15,
        'name' => "Caixa Gourmet (12 Brownies)",
        'price' => 89.90,
        'image' => "img/products/product-7.png",
        'description' => "Uma seleção de doze brownies dos nossos sabores favoritos.",
        'is_bestseller' => false,
        'is_featured' => false,
        'is_new' => false,
        'rating' => 4.8,
        'reviews_count' => 8,
        'is_box' => true
    ],
    [
        'id' => 16,
        'name' => "Caixa Festa (24 Brownies)",
        'price' => 169.90,
        'image' => "img/products/product-13.png",
        'description' => "Vinte e quatro unidades para dividir com toda a família.",
        'is_bestseller' => false,
        'is_featured' => false,
        'is_new' => false,
        'rating' => 5.0,
        'reviews_count' => 4,
        'is_box' => true
    ],
       [
        'id' => 17,
        'name' => "Caixa Festa (24 Brownies)",
        'price' => 169.90,
        'image' => "img/products/product-13.png",
        'description' => "Vinte e quatro unidades para dividir com toda a família.",
        'is_bestseller' => false,
        'is_featured' => false,
        'is_new' => false,
        'rating' => 5.0,
        'reviews_count' => 4,
        'is_box' => true
    ],
];

if (basename($_SERVER['PHP_SELF']) == basename(__FILE__)) {
    header('Content-Type: application/json');
    echo json_encode($products);
    exit;
}
